### ISSUE TITLE
Allow specifying artifacts subdirectory based on PR number

### ISSUE THREAD

**Issue by Shoeboxam** [gavv/pull-request-artifacts#62]
When any two files share the same basename, but are located in different folders, the artifacts are [uploaded to the same location](https://github.com/gavv/pull-request-artifacts/blob/main/src/main.ts#L168-L171), overwriting each other. Would you accept a PR that preserves the file structure in the artifacts/destination repository?

I would instead upload to `/{PR_NUMBER}/path/to/basename`. I do something similar in my fork, but would like to contribute my changes upstream.

Thanks!

**Comment by gavv** [comment]
Hi, sorry for delay! Yes, this sounds reasonable and PRs are welcome. I think the new behavior should be enabled by an option, disabled by default, to keep compatibility for existing users.

**Comment by gavv** [comment]
@Shoeboxam Hi! I've adopted most changes from [your fork](https://github.com/opendp/pull-request-artifacts/), thanks for sharing them!

* 63612db44e1ef4198db7e1d1f5f29da49c56c5e9 - add `inter-link` parameter; use to disable linking commit to PR
* 5bbcaeeecfc68d9dfac899d96970013eca214d76 - add `post-comment` parameter; use to disable posting comment
* 2355c3d4594ef7f8c4a92afb85705a724753ffc5 - add `comment-title` parameter; use to provide custom title
* f1a99ebc3e45977d56653210127d268438084ab7 - add `comment-style` parameter; use `table` for existing style and `list` for style similar to [this](https://github.com/opendp/opendp/pull/934#issuecomment-1733177889) (I think it makes sense, so I replicated it)
* 1f58dc37e72cc351ec62c32186120c7baeeee955 - deprecate `artifacts-dir` and introduce `artifacts-prefix`; new parameter allows to overwrite default "prNNN-" prefix; it can contain slashes and hence replaces `artifacts-dir` as well
* 743b3194a45ec7c68d9cd6942074f2b208067fea - add `preserve-path` parameter; use to preserve artifact path instead of using only its base name

See README for details.

For your needs in opendp, configuration may look like this:

```
      - name: Pull request artifacts
        uses: opendp/pull-request-artifacts@v2
        with:
          ...
          artifacts-repo: opendp/artifacts
          # note trailing slash
          artifacts-prefix: "PR/${{ github.event.number }}/"
          preserve-path: true
          inter-link: false
          comment-title: Your title
          comment-style: list
```

I've tagged release that includes these changes: https://github.com/gavv/pull-request-artifacts/releases/tag/v2.0.0

I'm going to close this issue, seem that the original request is now implemented. However, feel free to reopen or create additional issues / PRs if needed.
